# Generated by Django 4.1.3 on 2022-11-22 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalServicesBoard', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='body',
        ),
    ]
