# Generated by Django 4.1.3 on 2022-11-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalServicesBoard', '0005_classified_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='area',
            field=models.TextField(max_length=50),
        ),
    ]
