# Generated by Django 4.1.3 on 2022-11-25 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalServicesBoard', '0006_alter_classified_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
